language: node_js
node_js:
- '6'
before_script:
- npm install -g webpack
- npm install -g codecov
before_deploy:
- npm run deploy
deploy:
  provider: heroku
  api_key:
    secure: 863586ab-b54d-4028-bf19-e6e7c56c8add
  app: marcinkotyrba-jaa-ui
  on:
    repo: marcinkotyrba/JAlgoArena-UI
